import {calcCommission,commissionSummary,financeSummary} from './model.mjs';
import {missingReceipts,validateReceipt,receiptLimit} from './receipts.mjs';
import {initReconciliation} from './reconciliation-ui.mjs';
'use strict';
const $=s=>document.querySelector(s),fmt=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'});let state=null,toastTimer;
const bankUI=initReconciliation({getState:()=>state,save:async(action,p)=>{state=await call(action,p);render();},notify,fmt,today});
const receiptField=document.createElement('div');receiptField.className='wide';const receiptHeading=document.createElement('label');receiptHeading.textContent='Justificatif (JPEG, PNG ou PDF, 5 Mo maximum)';receiptHeading.htmlFor='receipt-file';receiptField.append(receiptHeading);
const receiptInput=document.createElement('input');receiptInput.id='receipt-file';receiptInput.type='file';receiptInput.accept='image/jpeg,image/png,application/pdf';receiptField.append(receiptInput);
const receiptStatus=document.createElement('small');receiptField.append(receiptStatus);
const receiptRemove=document.createElement('input');receiptRemove.type='checkbox';
const receiptRemoveLabel=document.createElement('label');receiptRemoveLabel.className='receipt-option';receiptRemoveLabel.textContent='Retirer le ticket (conservé dans la corbeille)';receiptRemoveLabel.prepend(receiptRemove);receiptField.append(receiptRemoveLabel);
const receiptExempt=document.createElement('input');receiptExempt.type='checkbox';const exemptLabel=document.createElement('label');exemptLabel.className='receipt-option';exemptLabel.textContent='Justificatif non requis';exemptLabel.prepend(receiptExempt);receiptField.append(exemptLabel);
$('#expense-form .fields').append(receiptField);
const receiptMetric=document.createElement('article');const receiptMetricBody=document.createElement('div');const receiptMetricTitle=document.createElement('h2');receiptMetricTitle.textContent='Tickets à retrouver';const receiptCount=document.createElement('strong');receiptMetricBody.append(receiptMetricTitle,receiptCount);receiptMetric.append(receiptMetricBody);$('.metrics').append(receiptMetric);
function resetReceipt(){receiptInput.value='';receiptRemove.checked=false;receiptExempt.checked=false;receiptStatus.textContent='';receiptRemoveLabel.hidden=true;}
function downloadReceipt(r){const bytes=Uint8Array.from(atob(r.data),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:r.type}));const a=document.createElement('a');a.href=url;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function selectedReceipt(){const file=receiptInput.files[0];if(!file)return null;if(file.size>receiptLimit)throw Error('Ticket trop volumineux : 5 Mo maximum.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Lecture du ticket impossible.'));reader.readAsDataURL(file);});return validateReceipt({name:file.name,type:file.type,size:file.size,data});}
function text(id,value){const el=$(id);if(el)el.textContent=value;}
window.addEventListener('error',e=>notify(`Erreur de démarrage : ${e.message}`,true));
window.addEventListener('unhandledrejection',e=>notify(`Erreur : ${e.reason?.message||e.reason||'action impossible'}`,true));
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function notify(msg,error=false){$('#toast').textContent=msg;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,error?14000:7000);}
async function call(action,data){if(!window.gestion)throw Error('Le module de stockage n’a pas démarré. Recharge la page depuis son adresse HTTPS.');const r=await window.gestion.call(action,data);if(!r.ok)throw Error(r.error);return r.data;}
function view(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===name));window.scrollTo(0,0);}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function item(row,actions,type='expense'){const el=document.createElement('div');el.className='row';const left=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('small');title.textContent=row.label;sub.textContent=`${row.day.split('-').reverse().join('/')} · ${row.category}${row.ref?' · Réf. '+row.ref:''}${row.historical?' · Historique':''}`;left.append(title,sub);const right=document.createElement('div'),amount=document.createElement('span');amount.className='amount';amount.textContent=fmt.format(row.cents/100);right.append(amount);if(actions){const buttons=document.createElement('div');buttons.className='row-actions';const edit=document.createElement('button');edit.textContent='Modifier';edit.onclick=()=>type==='revenue'?editRevenue(row):editExpense(row);const del=document.createElement('button');del.textContent='Supprimer';del.onclick=()=>type==='revenue'?removeRevenue(row.id):remove(row.id);buttons.append(edit,del);right.append(buttons);}el.append(left,right);return el;}
function list(target,rows,actions,type='expense'){const host=$(target);host.replaceChildren();if(!rows.length){const e=document.createElement('p');e.className='empty';e.textContent=type==='revenue'?'Aucune recette à afficher.':'Aucune dépense à afficher.';host.append(e);}else rows.forEach(row=>{const el=item(row,actions,type);if(type==='expense'&&actions){const tools=document.createElement('div');tools.className='row-actions';if(row.receipt){const button=document.createElement('button');button.textContent='Télécharger le ticket';button.onclick=()=>downloadReceipt(row.receipt);tools.append(button);}else{const status=document.createElement('small');status.textContent=missingReceipts([row])?'Ticket manquant':'Justificatif non requis';tools.append(status);}if(row.receiptTrash?.length){const button=document.createElement('button');button.textContent=`Corbeille (${row.receiptTrash.length})`;button.onclick=()=>showReceiptTrash(row);tools.append(button);}el.firstChild.append(tools);}host.append(el);});}
function showReceiptTrash(row){const dialog=document.createElement('dialog'),heading=document.createElement('h2');heading.textContent='Corbeille des justificatifs';dialog.append(heading);row.receiptTrash.forEach((r,index)=>{const line=document.createElement('p'),name=document.createElement('span'),download=document.createElement('button'),restore=document.createElement('button');name.textContent=r.name+' ';download.textContent='Télécharger';download.onclick=()=>downloadReceipt(r);restore.textContent='Restaurer';restore.onclick=async()=>{try{state=await call('restoreReceipt',{id:row.id,index});dialog.close();render();notify('Justificatif restauré.');}catch(e){notify(e.message,true);}};line.append(name,download,restore);dialog.append(line);});const close=document.createElement('button');close.textContent='Fermer';close.onclick=()=>dialog.close();dialog.append(close);dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);dialog.showModal();}
function render(){if(!state)return;const year=new Date().getFullYear(),elapsed=new Date().getMonth()+1;const annualExpenses=state.expenses.filter(r=>r.day.slice(0,4)===String(year)&&r.day<=today());const annualRevenues=state.revenues.filter(r=>r.day.slice(0,4)===String(year)&&r.day<=today());const total=annualExpenses.reduce((s,r)=>s+r.cents,0);const revenueTotal=annualRevenues.reduce((s,r)=>s+r.cents,0);const cashflow=revenueTotal-total;const commissions=commissionSummary(state.revenues,year);const finance=financeSummary(state,year);const balance=state.setup?state.setup.balance+state.revenues.filter(r=>r.day<=today()).reduce((s,r)=>s+r.cents,0)-state.expenses.filter(r=>!r.historical&&r.day<=today()).reduce((s,r)=>s+r.cents,0):null;const freeCash=balance===null?null:balance-finance.reserved;
 text('#year',year);text('#balance',balance===null?'—':fmt.format(balance/100));text('#revenue-total',fmt.format(revenueTotal/100));text('#total',fmt.format(total/100));text('#cashflow',fmt.format(cashflow/100));text('#vat-net',fmt.format(finance.vatNet/100));text('#urssaf-reserve',fmt.format(finance.urssafReserve/100));text('#free-cash',freeCash===null?'—':fmt.format(freeCash/100));$('#setup-callout').hidden=!!state.setup;
 const totals=Array(12).fill(0);annualExpenses.forEach(r=>totals[Number(r.day.slice(5,7))-1]+=r.cents);const max=Math.max(...totals,100);const chart=$('#chart');if(chart){chart.replaceChildren();totals.forEach((amount,i)=>{const col=document.createElement('div');col.className='month';const bar=document.createElement('div');bar.className='bar';bar.style.height=`${amount/max*100}%`;bar.title=fmt.format(amount/100);const label=document.createElement('small');label.textContent=['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sept','Oct','Nov','Déc'][i];col.append(bar,label);chart.append(col);});}text('#average',`Moyenne sur ${elapsed} mois : ${fmt.format(total/100/elapsed)}`);text('#chart-limit',total?`Maximum : ${fmt.format(max/100)}`:'Aucune dépense cette année');
 text('#list-count',state.expenses.length);text('#revenue-list-count',state.revenues.length);list('#recent',state.expenses.slice(0,3),false);filterList();filterRevenueList();text('#backup-status',state.backupFolder?'Copie de l’état précédent avant chaque changement':'Aucun dossier choisi');text('#data-path','Données : '+state.dataPath);text('#folder-path',state.backupFolder?'Sauvegardes : '+state.backupFolder:'Choisis un dossier pour activer les copies automatiques.');
 text('#connection-status',state.connected?'Dossier ouvert : '+state.dataPath:'Ouvre ton dossier pour retrouver tes comptes.');const setupForm=$('#setup-form');Array.from(setupForm.elements).forEach(e=>e.disabled=!state.connected||!!state.setup);if(!state.setup){text('#setup-summary','');setupForm.reset();setupForm.elements.day.value=today();}if(state.setup){const f=$('#setup-form');f.elements.day.value=state.setup.day;f.elements.balance.value=(state.setup.balance/100).toFixed(2);f.elements.next.value=state.setup.first;Array.from(f.elements).forEach(e=>e.disabled=true);text('#setup-summary','Point de départ enregistré.');}
 $('#save-expense').disabled=!state.setup;$('#save-revenue').disabled=!state.setup;text('#commission-cumul',`Cumul automatique ${year} : ${fmt.format(commissions.baseHt/100)} HT, calculé depuis ${commissions.count} recette${commissions.count>1?'s':''} Commission immobilière.`);historyHint();}
function filterList(){if(!state)return;bankUI.render();receiptCount.textContent=missingReceipts(state.expenses);const q=$('#search').value.toLocaleLowerCase('fr');list('#expense-list',state.expenses.filter(r=>`${r.label} ${r.category} ${r.ref??''}`.toLocaleLowerCase('fr').includes(q)),true);}
$('#search').addEventListener('input',filterList);
function filterRevenueList(){if(!state)return;const q=$('#revenue-search').value.toLocaleLowerCase('fr');list('#revenue-list',state.revenues.filter(r=>`${r.label} ${r.category}`.toLocaleLowerCase('fr').includes(q)),true,'revenue');}
$('#revenue-search').addEventListener('input',filterRevenueList);
const cents=v=>fmt.format(v/100);
function resultRow(label,value,highlight=false){const div=document.createElement('div');div.className='result-row'+(highlight?' highlight':'');const a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=typeof value==='number'?cents(value):value;div.append(a,b);return div;}
function runCommissionForm(form,host,compact=false){host.replaceChildren();try{const year=new Date().getFullYear(),summary=commissionSummary(state?.revenues||[],year);const data=Object.fromEntries(new FormData(form));const r=calcCommission({...data,previousHt:(summary.baseHt/100).toFixed(2)});const rows=compact?[resultRow('Commission conseiller TTC',r.advisorTtc,true),resultRow('TVA collectée',r.advisorVat),resultRow('URSSAF 25,6 %',r.urssaf),resultRow('Net estimé',r.net,true)]:[resultRow('Commission agence HT',r.agencyHt),resultRow('Base personnelle HT simulée',r.personalBaseHt),resultRow('Cumul personnel HT avant simulation',r.previousHt),resultRow('Cumul personnel HT après simulation',r.nextHt),resultRow('Commission conseiller HT',r.advisorHt,true),resultRow('TVA collectée estimée',r.advisorVat),resultRow('Commission conseiller TTC',r.advisorTtc),resultRow('URSSAF estimée 25,6 %',r.urssaf),resultRow('Net estimé après TVA et URSSAF',r.net,true)];host.append(...rows);}catch(err){notify(err.message,true);}}
$('#commission-form').onsubmit=e=>{e.preventDefault();runCommissionForm(e.target,$('#commission-result'));};
const dashCommissionForm=$('#dash-commission-form');if(dashCommissionForm)dashCommissionForm.onsubmit=e=>{e.preventDefault();runCommissionForm(e.target,$('#dash-commission-result'),true);};
const form=$('#expense-form');function resetForm(){form.reset();resetReceipt();form.elements.id.value='';form.elements.day.value=today();form.elements.vat.value='0';$('#form-heading').textContent='Ajouter une dépense';$('#save-expense').textContent='Enregistrer la dépense';$('#cancel-edit').hidden=true;historyHint();}
function historyHint(){const historical=state?.setup&&form.elements.day.value<state.setup.day;$('#history-field').hidden=!historical||!!form.elements.id.value;$('#historical-note').textContent=historical?'Historique : cette dépense comptera dans les statistiques, sans modifier le solde initial.':state?.setup?'La référence sera attribuée automatiquement.':'Commence par enregistrer ton point de départ dans Réglages.';}
form.elements.day.addEventListener('change',historyHint);$('#cancel-edit').onclick=resetForm;
function editExpense(r){view('expenses');resetReceipt();receiptStatus.textContent=r.receipt?r.receipt.name:'Aucun ticket lié';receiptRemoveLabel.hidden=!r.receipt;receiptExempt.checked=!!r.receiptExempt;for(const [key,value] of Object.entries({id:r.id,day:r.day,amount:(r.cents/100).toFixed(2),label:r.label,category:r.category,payment:r.payment,vat:(r.vat_cents/100).toFixed(2),notes:r.notes,ref:r.ref??''}))form.elements[key].value=value;$('#form-heading').textContent='Modifier la dépense';$('#save-expense').textContent='Enregistrer les changements';$('#cancel-edit').hidden=false;historyHint();}
form.onsubmit=async e=>{e.preventDefault();const button=$('#save-expense');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));if(data.id)data.id=Number(data.id);data.receipt=await selectedReceipt();data.removeReceipt=receiptRemove.checked&&!data.receipt;data.receiptExempt=receiptExempt.checked;state=await call('save',data);resetForm();render();notify(state.warning||'Dépense enregistrée sur cet ordinateur.',!!state.warning);}catch(err){notify(err.message,true);}finally{button.disabled=!state?.setup;}};
const revenueForm=$('#revenue-form');function resetRevenueForm(){revenueForm.reset();revenueForm.elements.id.value='';revenueForm.elements.day.value=today();revenueForm.elements.vat.value='0';$('#revenue-form-heading').textContent='Ajouter une recette';$('#save-revenue').textContent='Enregistrer la recette';$('#cancel-revenue-edit').hidden=true;}
$('#cancel-revenue-edit').onclick=resetRevenueForm;
function editRevenue(r){view('revenues');for(const [key,value] of Object.entries({id:r.id,day:r.day,amount:(r.cents/100).toFixed(2),label:r.label,category:r.category,vat:(r.vat_cents/100).toFixed(2),notes:r.notes}))revenueForm.elements[key].value=value;$('#revenue-form-heading').textContent='Modifier la recette';$('#save-revenue').textContent='Enregistrer les changements';$('#cancel-revenue-edit').hidden=false;}
revenueForm.onsubmit=async e=>{e.preventDefault();const button=$('#save-revenue');button.disabled=true;try{const data=Object.fromEntries(new FormData(revenueForm));if(data.id)data.id=Number(data.id);state=await call('saveRevenue',data);resetRevenueForm();render();notify(state.warning||'Recette enregistrée sur cet ordinateur.',!!state.warning);}catch(err){notify(err.message,true);}finally{button.disabled=!state?.setup;}};
async function remove(id){const d=$('#delete-dialog');d.returnValue='cancel';d.showModal();d.addEventListener('close',async()=>{if(d.returnValue!=='confirm')return;try{state=await call('remove',id);if(Number(form.elements.id.value)===id)resetForm();render();notify(state.warning||'Dépense supprimée. La liste des références est recalculée.',!!state.warning);}catch(e){notify(e.message,true);}},{once:true});}
async function removeRevenue(id){const d=$('#delete-revenue-dialog');d.returnValue='cancel';d.showModal();d.addEventListener('close',async()=>{if(d.returnValue!=='confirm')return;try{state=await call('removeRevenue',id);if(Number(revenueForm.elements.id.value)===id)resetRevenueForm();render();notify(state.warning||'Recette supprimée.',!!state.warning);}catch(e){notify(e.message,true);}},{once:true});}
$('#setup-form').elements.day.value=today();$('#setup-form').onsubmit=async e=>{e.preventDefault();$('#save-setup').disabled=true;try{state=await call('setup',Object.fromEntries(new FormData(e.target)));render();notify(state.warning||'Point de départ enregistré. Tu peux saisir une dépense de test.',!!state.warning);}catch(err){$('#save-setup').disabled=false;notify(err.message,true);}};
async function backup(choose=false){try{const data=await call('backup',{choose});if(data.cancelled)return;state=data;render();notify('Sauvegarde créée : '+data.file);}catch(e){notify(e.message,true);}}
function bindClick(id,fn){const el=$(id);if(el)el.addEventListener('click',fn);}
bindClick('#backup-main',()=>backup());bindClick('#backup-now',()=>backup());
async function connect(e){const button=e?.currentTarget;try{if(button)button.disabled=true;notify('Ouverture du sélecteur de dossier...');state=await call('connect');resetForm();resetRevenueForm();bankUI.reset();render();if(state.setup&&window.innerWidth>=1000)view('bank');notify('Dossier ouvert. Les comptes restent enregistrés sur ce PC.');}catch(e){notify(e.message,true);}finally{if(button)button.disabled=false;}}
bindClick('#choose-backup',connect);bindClick('#connect',connect);bindClick('#restore',async()=>{try{const data=await call('restore');if(data.cancelled)return;state=data;resetForm();render();notify('Sauvegarde restaurée. Une copie de l’état précédent a été conservée.');}catch(e){notify(e.message,true);}});
resetForm();resetRevenueForm();call('state').then(data=>{state=data;render();}).catch(e=>notify(e.message,true));
