'use strict';
const $=s=>document.querySelector(s),fmt=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'});let state=null,toastTimer;
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function notify(msg,error=false){$('#toast').textContent=msg;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,error?14000:7000);}
async function call(action,data){if(!window.gestion)throw Error('Le module de stockage n’a pas démarré. Recharge la page depuis son adresse HTTPS.');const r=await window.gestion.call(action,data);if(!r.ok)throw Error(r.error);return r.data;}
function view(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===name));window.scrollTo(0,0);}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
function item(row,actions){const el=document.createElement('div');el.className='row';const left=document.createElement('div'),title=document.createElement('strong'),sub=document.createElement('small');title.textContent=row.label;sub.textContent=`${row.day.split('-').reverse().join('/')} · ${row.category}${row.ref?' · Réf. '+row.ref:''}${row.historical?' · Historique':''}`;left.append(title,sub);const right=document.createElement('div'),amount=document.createElement('span');amount.className='amount';amount.textContent=fmt.format(row.cents/100);right.append(amount);if(actions){const buttons=document.createElement('div');buttons.className='row-actions';const edit=document.createElement('button');edit.textContent='Modifier';edit.onclick=()=>editExpense(row);const del=document.createElement('button');del.textContent='Supprimer';del.onclick=()=>remove(row.id);buttons.append(edit,del);right.append(buttons);}el.append(left,right);return el;}
function list(target,rows,actions){const host=$(target);host.replaceChildren();if(!rows.length){const e=document.createElement('p');e.className='empty';e.textContent='Aucune dépense à afficher.';host.append(e);}else rows.forEach(row=>host.append(item(row,actions)));}
function render(){if(!state)return;const year=new Date().getFullYear(),elapsed=new Date().getMonth()+1;const annual=state.expenses.filter(r=>r.day.slice(0,4)===String(year)&&r.day<=today());const total=annual.reduce((s,r)=>s+r.cents,0);const balance=state.setup?state.setup.balance-state.expenses.filter(r=>!r.historical&&r.day<=today()).reduce((s,r)=>s+r.cents,0):null;
 $('#year').textContent=year;$('#balance').textContent=balance===null?'—':fmt.format(balance/100);$('#total').textContent=fmt.format(total/100);$('#count').textContent=state.expenses.length;$('#next').textContent=state.next??'—';$('#setup-callout').hidden=!!state.setup;
 const totals=Array(12).fill(0);annual.forEach(r=>totals[Number(r.day.slice(5,7))-1]+=r.cents);const max=Math.max(...totals,100);$('#chart').replaceChildren();totals.forEach((amount,i)=>{const col=document.createElement('div');col.className='month';const bar=document.createElement('div');bar.className='bar';bar.style.height=`${amount/max*100}%`;bar.title=fmt.format(amount/100);const label=document.createElement('small');label.textContent=['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Août','Sept','Oct','Nov','Déc'][i];col.append(bar,label);$('#chart').append(col);});$('#average').textContent=`Moyenne sur ${elapsed} mois : ${fmt.format(total/100/elapsed)}`;$('#chart-limit').textContent=total?`Maximum : ${fmt.format(max/100)}`:'Aucune dépense cette année';
 $('#list-count').textContent=state.expenses.length;list('#recent',state.expenses.slice(0,3),false);filterList();$('#backup-status').textContent=state.backupFolder?'Copie de l’état précédent avant chaque changement':'Aucun dossier choisi';$('#data-path').textContent='Données : '+state.dataPath;$('#folder-path').textContent=state.backupFolder?'Sauvegardes : '+state.backupFolder:'Choisis un dossier pour activer les copies automatiques.';
 $('#connection-status').textContent=state.connected?'Dossier ouvert : '+state.dataPath:'Ouvre ton dossier pour retrouver tes comptes.';const setupForm=$('#setup-form');Array.from(setupForm.elements).forEach(e=>e.disabled=!state.connected||!!state.setup);if(!state.setup){$('#setup-summary').textContent='';setupForm.reset();setupForm.elements.day.value=today();}if(state.setup){const f=$('#setup-form');f.elements.day.value=state.setup.day;f.elements.balance.value=(state.setup.balance/100).toFixed(2);f.elements.next.value=state.setup.first;Array.from(f.elements).forEach(e=>e.disabled=true);$('#setup-summary').textContent='Point de départ enregistré.';}
 $('#save-expense').disabled=!state.setup;historyHint();}
function filterList(){if(!state)return;const q=$('#search').value.toLocaleLowerCase('fr');list('#expense-list',state.expenses.filter(r=>`${r.label} ${r.category} ${r.ref??''}`.toLocaleLowerCase('fr').includes(q)),true);}
$('#search').addEventListener('input',filterList);
const form=$('#expense-form');function resetForm(){form.reset();form.elements.id.value='';form.elements.day.value=today();form.elements.vat.value='0';$('#form-heading').textContent='Ajouter une dépense';$('#save-expense').textContent='Enregistrer la dépense';$('#cancel-edit').hidden=true;historyHint();}
function historyHint(){const historical=state?.setup&&form.elements.day.value<state.setup.day;$('#history-field').hidden=!historical||!!form.elements.id.value;$('#historical-note').textContent=historical?'Historique : cette dépense comptera dans les statistiques, sans modifier le solde initial.':state?.setup?'La référence sera attribuée automatiquement.':'Commence par enregistrer ton point de départ dans Réglages.';}
form.elements.day.addEventListener('change',historyHint);$('#cancel-edit').onclick=resetForm;
function editExpense(r){view('expenses');for(const [key,value] of Object.entries({id:r.id,day:r.day,amount:(r.cents/100).toFixed(2),label:r.label,category:r.category,payment:r.payment,vat:(r.vat_cents/100).toFixed(2),notes:r.notes,ref:r.ref??''}))form.elements[key].value=value;$('#form-heading').textContent='Modifier la dépense';$('#save-expense').textContent='Enregistrer les changements';$('#cancel-edit').hidden=false;historyHint();}
form.onsubmit=async e=>{e.preventDefault();const button=$('#save-expense');button.disabled=true;try{const data=Object.fromEntries(new FormData(form));if(data.id)data.id=Number(data.id);state=await call('save',data);resetForm();render();notify(state.warning||'Dépense enregistrée sur cet ordinateur.',!!state.warning);}catch(err){notify(err.message,true);}finally{button.disabled=!state?.setup;}};
async function remove(id){const d=$('#delete-dialog');d.returnValue='cancel';d.showModal();d.addEventListener('close',async()=>{if(d.returnValue!=='confirm')return;try{state=await call('remove',id);if(Number(form.elements.id.value)===id)resetForm();render();notify(state.warning||'Dépense supprimée. Sa référence reste réservée.',!!state.warning);}catch(e){notify(e.message,true);}},{once:true});}
$('#setup-form').elements.day.value=today();$('#setup-form').onsubmit=async e=>{e.preventDefault();$('#save-setup').disabled=true;try{state=await call('setup',Object.fromEntries(new FormData(e.target)));render();notify(state.warning||'Point de départ enregistré. Tu peux saisir une dépense de test.',!!state.warning);}catch(err){$('#save-setup').disabled=false;notify(err.message,true);}};
async function backup(choose=false){try{const data=await call('backup',{choose});if(data.cancelled)return;state=data;render();notify('Sauvegarde créée : '+data.file);}catch(e){notify(e.message,true);}}
$('#backup-main').onclick=()=>backup();$('#backup-now').onclick=()=>backup();async function connect(){try{state=await call('connect');resetForm();render();notify('Dossier ouvert. Les comptes restent enregistrés sur ce PC.');}catch(e){notify(e.message,true);}}$('#choose-backup').onclick=connect;$('#connect').onclick=connect;$('#restore').onclick=async()=>{try{const data=await call('restore');if(data.cancelled)return;state=data;resetForm();render();notify('Sauvegarde restaurée. Une copie de l’état précédent a été conservée.');}catch(e){notify(e.message,true);}};
resetForm();call('state').then(data=>{state=data;render();}).catch(e=>notify(e.message,true));
